#!/usr/bin/env python
import logging

from terraform_provider import plugin
import terraform_provider_example

if __name__ == '__main__':
    logging.basicConfig(level='INFO')
    plugin.serve(terraform_provider_example.ExampleProvider())
