#!/usr/bin/env python
import logging

import terraform_provider.plugin.server
import terraform_provider_example

if __name__ == '__main__':
    logging.basicConfig(level='INFO')
    terraform_provider.plugin.server.serve(terraform_provider_example.ExampleProvider())
